# Values for gramnuri-web in dev environment
replicas: 1

image:
  repository: ghcr.io/igh9410/gramnuri-web
  tag: fe3164ae5100d77e21811cb8abae8a116df57d2b

containerPort: 3000

service:
  port: 80
  portName: http

httproute:
  gateway:
    name: gateway
    namespace: kube-system
  hostnames:
    - dev.landskipifyai.com

resources:
  requests:
    cpu: 100m
    memory: 100Mi

envFrom:
  - secretRef:
      name: gramnuri-client-secrets

nodeSelector:
  kubernetes.io/arch: amd64
  kubernetes.io/os: linux

imagePullSecrets:
  - name: ghcr-image-pull-secrets

serviceMonitor:
  enabled: false
