apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "generic-app.name" . }}-httproute
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: {{ .Values.httproute.gateway.name }}
      namespace: {{ .Values.httproute.gateway.namespace }}
  hostnames:
    {{- toYaml .Values.httproute.hostnames | nindent 4 }}
  rules:
    - backendRefs:
        - name: {{ include "generic-app.name" . }}
          port: {{ .Values.service.port }}
