{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "generic-app.name" . }}
  labels:
    app: {{ include "generic-app.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "generic-app.name" . }}
  endpoints:
    - port: {{ .Values.service.portName | default "http" }}
      path: {{ .Values.serviceMonitor.path | default "/metrics" }}
      interval: {{ .Values.serviceMonitor.interval | default "30s" }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout | default "10s" }}
{{- end }}
