apiVersion: v1
kind: Service
metadata:
  name: { { include "generic-app.name" . } }
  labels:
    app: { { include "generic-app.name" . } }
spec:
  ports:
    - name: { { .Values.service.portName | default "http" } }
      port: { { .Values.service.port } }
      targetPort: { { .Values.containerPort } }
  selector:
    app: { { include "generic-app.name" . } }
  type: { { .Values.service.type | default "ClusterIP" } }
