# Default values for generic-app chart
nameOverride: ""

replicas: 1

image:
  repository: ""
  tag: "latest"

containerPort: 8080

service:
  port: 80
  portName: http
  type: ClusterIP

httproute:
  gateway:
    name: gateway
    namespace: kube-system
  hostnames: []

resources: {}

envFrom: []

nodeSelector:
  kubernetes.io/arch: amd64
  kubernetes.io/os: linux

imagePullSecrets: []

serviceMonitor:
  enabled: false
  path: "/metrics"
  interval: "30s"
  scrapeTimeout: "10s"
