apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: artskorner-api
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: artskorner-api-ingress
  - path: httproute-patch.yaml
    target:
      kind: HTTPRoute
      name: artskorner-api-httproute
images:
  - name: ghcr.io/igh9410/artskorner-api
    newTag: dfd512e774807626c999833caf5e9c0f78396259
